### ISSUE TITLE
Numeric Comparison function

### ISSUE THREAD

**Issue by navinsubramani** [navinsubramani/LabVIEW-Script-Language#12]
Add functions that make comparison actions on the numeric.

Equal to
Not Equal to
Greater than
Greater than or equal to
Lesser than
Lesser than or equal to

**Comment by pranay001** [comment]
Its implemented Navin, I will add CHM document to this function and then I will close this issue.

**Comment by navinsubramani** [comment]
Closing this issue for now as the CHM documentation requirement is added to the other issues
