### ISSUE TITLE
Loops & Structures functions

### ISSUE THREAD

**Issue by navinsubramani** [navinsubramani/LabVIEW-Script-Language#13]
- For Loop
- While Loop
- If, If else, else
- Switch

**Comment by pranay001** [comment]
while loop is implemented as expected, with syntax **while($continue?$)**. where continue? is a boolean type which helps in making a decision whether to execute the while loop or now.

But what can be the syntax for For Loop, take the below different types of for loops.

- for(i=0;i<n;i++)

- for(i=0,j=0;(i<n)&&(j<n);i=i+j-1,j=j+1)

Also, the execution of for loop has to be as shown below.1->2->3

![image](https://user-images.githubusercontent.com/22153041/63287404-e3f8c780-c2d7-11e9-8192-5bf06579d7d3.png)

but in our case, our execution will be as denoted by arrow.

Please give your suggestions to proceed further.

**Comment by navinsubramani** [comment]
For loop has a lot of cases but in general, the structure is,

for(Initialize Variables; Condition Statement;Update Variables)
-> One Indent

It is easier to handle the 'Condition statement' using functions and 'indent' like any other structure.

The challenge here is that the 'Init Variables' and 'Update Variables' part could be a bit flexible and can have many functions or statements with comma-separated values.

Though it is easier to implement the 'for(i=1; any condition;i=i+1) - We can start with it

But somehow I feel if you add the function for comma separator as $anything$,$anything$ - there is a chance that the framework would intelligently pick the $anything$ as a function and do the needful. Please try this and let me know - I guess we should be able to implement this without any issues given the tool is CRAZY in its capabilities :)
