### ISSUE TITLE
Python equivalent Scripts

### ISSUE THREAD

**Issue by navinsubramani** [navinsubramani/LabVIEW-Script-Language#39]
Compare the existing function with the python equivalent scripts using https://www.w3schools.com/python/default.asp

So, all the scripts developed using the LSL will be python compatible and could be used by engineers with their existing Python knowledge

**Comment by pranay001** [comment]
In LSL we have the comment lines using the identifier "\\", but in python we use "#" for single-line comment. Please update it    @navinsubramani .
