### ISSUE TITLE
String operations syntax defining

### ISSUE THREAD

**Issue by pranay001** [navinsubramani/LabVIEW-Script-Language#8]
Please comment your opinion on the below syntax formats and also add if few other functionalities are required.

String functions:

String length.
Syntax: strlen($string$)

Concat string
Syntax: concat($a$,$b$)

Substring
Syntax: substr($string$,$offset$,$length$)

Toupper case
Syntax: toupper($string$)

Tolower case
Syntax: tolower($string$)

Is empty?
Syntax: isempty($string$)

**Comment by navinsubramani** [comment]
The above looks good. Please also add the following functionalities,

Anything to string,
str($anything$)

String Concatenation,
$string1$ + $string2$

**Comment by pranay001** [comment]
I added all the functions but I would like to check from you whether shall we have str($anything$) function in string operations or as a part of typecast operations

**Comment by navinsubramani** [comment]
Make sense to add them to a typecast library for now

**Comment by navinsubramani** [comment]
This is kept in String Operations since there is no typecast library
